import React, { useState, useRef, useEffect, useCallback } from 'react';
import { ProfileAnalysis, GeneratedHeadline } from '@/shared/types';
import { SECTION_LABELS } from '@/shared/constants';

interface ExportMenuProps {
  analysis: ProfileAnalysis | null;
  headlines: GeneratedHeadline[];
  summaryText: string;
  summaryTone: string;
  onToast: (message: string, type: 'success' | 'error' | 'info') => void;
}

function buildMarkdown(analysis: ProfileAnalysis | null, headlines: GeneratedHeadline[], summaryText: string, summaryTone: string): string {
  const lines: string[] = [];
  lines.push('# ProfileForge AI Analysis Report');
  lines.push(`> Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('');

  if (analysis) {
    lines.push('## Profile Score');
    lines.push(`**Overall Score: ${analysis.overallScore}/100**`);
    lines.push('');

    if (analysis.topStrengths.length > 0) {
      lines.push('### Strengths');
      analysis.topStrengths.forEach(s => lines.push(`- ${s}`));
      lines.push('');
    }

    lines.push('### Section Breakdown');
    lines.push('| Section | Score | Max | Percentage |');
    lines.push('|---------|-------|-----|------------|');
    analysis.sections.forEach(s => {
      const pct = Math.round((s.score / s.maxScore) * 100);
      lines.push(`| ${SECTION_LABELS[s.key] || s.key} | ${s.score} | ${s.maxScore} | ${pct}% |`);
    });
    lines.push('');

    lines.push('### Detailed Feedback');
    analysis.sections.forEach(s => {
      lines.push(`#### ${SECTION_LABELS[s.key] || s.key} (${s.score}/${s.maxScore})`);
      lines.push(s.feedback);
      if (s.suggestions.length > 0) {
        lines.push('');
        lines.push('**Suggestions:**');
        s.suggestions.forEach(sg => lines.push(`- ${sg}`));
      }
      lines.push('');
    });

    if (analysis.topImprovements.length > 0) {
      lines.push('### Top Improvements');
      analysis.topImprovements.forEach((imp, i) => lines.push(`${i + 1}. ${imp}`));
      lines.push('');
    }
  }

  if (headlines.length > 0) {
    lines.push('## Generated Headlines');
    headlines.forEach((h, i) => {
      lines.push(`${i + 1}. **${h.text}**`);
      lines.push(`   - Tone: ${h.tone} | Impact: ${h.impact}`);
    });
    lines.push('');
  }

  if (summaryText) {
    lines.push(`## Generated Summary (${summaryTone})`);
    lines.push(summaryText);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by ProfileForge AI - LinkedIn Profile Optimizer*');

  return lines.join('\n');
}

function buildPlainText(analysis: ProfileAnalysis | null, headlines: GeneratedHeadline[], summaryText: string, summaryTone: string): string {
  const lines: string[] = [];
  lines.push('PROFILEFORGE AI ANALYSIS REPORT');
  lines.push('='.repeat(40));
  lines.push(`Generated: ${new Date().toLocaleDateString()}`);
  lines.push('');

  if (analysis) {
    lines.push(`OVERALL SCORE: ${analysis.overallScore}/100`);
    lines.push('-'.repeat(30));

    if (analysis.topStrengths.length > 0) {
      lines.push('');
      lines.push('STRENGTHS:');
      analysis.topStrengths.forEach(s => lines.push(`  * ${s}`));
    }

    lines.push('');
    lines.push('SECTION BREAKDOWN:');
    analysis.sections.forEach(s => {
      const pct = Math.round((s.score / s.maxScore) * 100);
      lines.push(`  ${SECTION_LABELS[s.key] || s.key}: ${s.score}/${s.maxScore} (${pct}%)`);
      lines.push(`    ${s.feedback}`);
      if (s.suggestions.length > 0) {
        s.suggestions.forEach(sg => lines.push(`    - ${sg}`));
      }
      lines.push('');
    });

    if (analysis.topImprovements.length > 0) {
      lines.push('TOP IMPROVEMENTS:');
      analysis.topImprovements.forEach((imp, i) => lines.push(`  ${i + 1}. ${imp}`));
      lines.push('');
    }
  }

  if (headlines.length > 0) {
    lines.push('GENERATED HEADLINES:');
    lines.push('-'.repeat(30));
    headlines.forEach((h, i) => {
      lines.push(`  ${i + 1}. ${h.text}`);
      lines.push(`     Tone: ${h.tone} | Impact: ${h.impact}`);
    });
    lines.push('');
  }

  if (summaryText) {
    lines.push(`GENERATED SUMMARY (${summaryTone.toUpperCase()}):`);
    lines.push('-'.repeat(30));
    lines.push(summaryText);
    lines.push('');
  }

  lines.push('Generated by ProfileForge AI');
  return lines.join('\n');
}

export function ExportMenu({ analysis, headlines, summaryText, summaryTone, onToast }: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const hasContent = analysis || headlines.length > 0 || summaryText;

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const copyMarkdown = useCallback(() => {
    const md = buildMarkdown(analysis, headlines, summaryText, summaryTone);
    navigator.clipboard.writeText(md).then(() => {
      onToast('Copied as Markdown', 'success');
    }).catch(() => {
      onToast('Failed to copy', 'error');
    });
    setOpen(false);
  }, [analysis, headlines, summaryText, summaryTone, onToast]);

  const downloadTxt = useCallback(() => {
    const txt = buildPlainText(analysis, headlines, summaryText, summaryTone);
    const blob = new Blob([txt], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `profileforge-report-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    onToast('Downloaded as .txt', 'success');
    setOpen(false);
  }, [analysis, headlines, summaryText, summaryTone, onToast]);

  const printPDF = useCallback(() => {
    window.print();
    onToast('Print dialog opened', 'info');
    setOpen(false);
  }, [onToast]);

  if (!hasContent) return null;

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setOpen(o => !o)}
        className="btn-ghost flex items-center gap-1.5 text-xs"
        title="Export results"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        Export
      </button>

      {open && (
        <div className="export-dropdown animate-scale-in">
          <div className="px-3 py-2 border-b border-border/30">
            <span className="text-2xs font-semibold text-text-tertiary uppercase tracking-wider">Export Results</span>
          </div>
          <button className="export-dropdown-item" onClick={copyMarkdown}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
            </svg>
            Copy Markdown
          </button>
          <button className="export-dropdown-item" onClick={downloadTxt}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
              <path d="M14 2v6h6M12 18v-6M9 15l3 3 3-3" />
            </svg>
            Download .txt
          </button>
          <button className="export-dropdown-item" onClick={printPDF}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            Print PDF
          </button>
        </div>
      )}
    </div>
  );
}
